<?php

declare(strict_types=1);

namespace PhpJs\Transpile;

use PhpJs\Builtins\BuiltinRegistry;
use PhpJs\Compiler\Ctx;
use PhpJs\Node\NodeHost;
use PhpParser\Node as P;
use PhpParser\Node\Expr;
use PhpParser\Node\Stmt;
use PhpParser\PrettyPrinter;

/**
 * Ahead-of-time compiles the modules a `node-compat` host loads.
 *
 * This is the build-time half in its most direct form: it hooks module
 * compilation, emits PHP for every function the emitter accepts, and registers
 * the result immediately. A production build would write the PHP to disk and
 * preload it (docs/aot-php.md §4 / phase 3); doing it in-process keeps phase 1
 * about whether the emitter is correct and fast enough, which is the open
 * question.
 *
 * `attach()` is a no-op for modules the filter rejects, so a build can convert
 * one library and leave the rest interpreted.
 */
final class NodeIntegration
{
    /** @var array<string, int> module path => functions converted */
    public array $converted = [];
    /** @var array<string, int> module path => functions considered */
    public array $seen = [];
    /** @var list<array{module: string, id: string, reason: string}> */
    public array $refused = [];
    public float $emitSeconds = 0.0;

    /** @var array<string, Expr\Closure> */
    private array $emitted = [];
    private static int $instance = 0;
    private readonly string $prefix;

    public function __construct(
        /** Return true for modules that should be compiled ahead of time. */
        private readonly \Closure $accept,
    ) {
        // Native IDs are process-wide; two hosts in one process must not
        // collide over the same module path.
        $this->prefix = 'aot' . (++self::$instance);
    }

    /** Compile every module whose path the filter accepts. */
    public function attach(NodeHost $host): void
    {
        $host->modules->onCompileModule = function (string $path): ?callable {
            if (!($this->accept)($path)) {
                return null;
            }
            $counter = 0;
            $this->seen[$path] = 0;
            $this->converted[$path] = 0;
            return function (object $node, Ctx $ctx, bool $isProgram) use ($path, &$counter): ?string {
                if ($isProgram) {
                    return null;
                }
                $this->seen[$path]++;
                $id = sprintf(
                    '%s:%s#%d%s',
                    $this->prefix,
                    hash('xxh128', $path),
                    $counter++,
                    $ctx->name !== '' ? ':' . preg_replace('/[^A-Za-z0-9_$]/', '', $ctx->name) : ''
                );
                $t = microtime(true);
                try {
                    $closure = (new FunctionEmitter($ctx))->emit($node);
                } catch (Unsupported $e) {
                    $this->refused[] = ['module' => $path, 'id' => $id, 'reason' => $e->getMessage()];
                    return null;
                } finally {
                    $this->emitSeconds += microtime(true) - $t;
                }
                $this->emitted[$id] = $closure;
                $this->converted[$path]++;
                // Register eagerly: the template is instantiated as soon as the
                // module runs, and JSFunction resolves its native at that point.
                BuiltinRegistry::registerHost([$id => $this->materialize($id, $closure)]);
                return $id;
            };
        };
    }

    /** @return list<array{reason: string, count: int}> refusals, most common first */
    public function refusalSummary(): array
    {
        $counts = [];
        foreach ($this->refused as $r) {
            $counts[$r['reason']] = ($counts[$r['reason']] ?? 0) + 1;
        }
        arsort($counts);
        $out = [];
        foreach ($counts as $reason => $count) {
            $out[] = ['reason' => $reason, 'count' => $count];
        }
        return $out;
    }

    public function totalConverted(): int
    {
        return array_sum($this->converted);
    }

    public function totalSeen(): int
    {
        return array_sum($this->seen);
    }

    /** The whole generated corpus as one loadable PHP file. */
    public function php(): string
    {
        $items = [];
        foreach ($this->emitted as $id => $closure) {
            $items[] = new P\ArrayItem($closure, new \PhpParser\Node\Scalar\String_($id));
        }
        $printer = new PrettyPrinter\Standard(['shortArraySyntax' => true]);
        return "<?php\n\n// Generated by php-js-transpile. Do not edit.\n\n"
            . $printer->prettyPrint([new Stmt\Return_(new Expr\Array_($items, ['kind' => Expr\Array_::KIND_SHORT]))])
            . "\n";
    }

    /**
     * Turn one emitted closure into a callable.
     *
     * `eval` is used here and only here, because this path compiles in-process;
     * the file-based path (§4) exists so opcache can hold the result, which
     * eval'd code never gets.
     */
    private function materialize(string $id, Expr\Closure $closure): callable
    {
        $printer = new PrettyPrinter\Standard(['shortArraySyntax' => true]);
        $code = $printer->prettyPrintExpr($closure);
        /** @var callable $fn */
        $fn = eval('return ' . $code . ';');
        return $fn;
    }
}
