<?php

declare(strict_types=1);

namespace PhpJs\Transpile;

use PhpJs\Compiler\Compiler;
use PhpJs\Compiler\Ctx;
use PhpParser\Node as P;
use PhpParser\Node\Expr;
use PhpParser\Node\Stmt;
use PhpParser\PrettyPrinter;

/**
 * Compiles the functions of one JS module to PHP, ahead of time.
 *
 * Runs the ordinary bytecode compiler with its per-function hook attached, so
 * the emitter sees exactly the scope analysis the bytecode was built from —
 * the same `Ctx`, the same slot numbers. That is not an optimization, it is
 * the correctness condition (docs/aot-php.md §3).
 *
 * Every function is attempted; the ones the emitter refuses simply stay as
 * bytecode. The output is a PHP file returning `[nativeId => closure]`, plus
 * the bytecode template with `nativeId` stamped on the functions that were
 * converted. Loading the PHP file is optional: the template runs either way.
 *
 * Build time only. Nothing here is on a request path.
 */
final class Transpiler
{
    /** @var array<string, Expr\Closure> */
    private array $emitted = [];
    /** @var list<array{id: string, reason: string}> */
    private array $refused = [];
    private int $seen = 0;

    public function __construct(
        /** Prefix for generated native IDs; must be stable across builds. */
        private readonly string $moduleId,
    ) {
    }

    /**
     * @return array{template: array<string, mixed>, php: string, converted: int, seen: int, refused: list<array{id: string, reason: string}>}
     */
    public function run(string $source): array
    {
        $this->emitted = [];
        $this->refused = [];
        $this->seen = 0;
        $counter = 0;

        $template = Compiler::compile($source, function (object $node, Ctx $ctx, bool $isProgram) use (&$counter): ?string {
            if ($isProgram) {
                return null; // the module wrapper itself stays interpreted
            }
            $this->seen++;
            // Position-derived so the ID is stable for a given source but
            // cannot be forged from source text: it is a counter plus the
            // function's own name, both emitter-controlled.
            $id = sprintf(
                '%s#%d%s',
                $this->moduleId,
                $counter++,
                $ctx->name !== '' ? ':' . preg_replace('/[^A-Za-z0-9_$]/', '', $ctx->name) : ''
            );
            try {
                $this->emitted[$id] = (new FunctionEmitter($ctx))->emit($node);
                return $id;
            } catch (Unsupported $e) {
                $this->refused[] = ['id' => $id, 'reason' => $e->getMessage()];
                return null;
            }
        });

        return [
            'template' => $template,
            'php' => $this->render(),
            'converted' => count($this->emitted),
            'seen' => $this->seen,
            'refused' => $this->refused,
        ];
    }

    /** The generated file: `<?php return [id => closure, ...];` */
    private function render(): string
    {
        $items = [];
        foreach ($this->emitted as $id => $closure) {
            $items[] = new P\ArrayItem($closure, new \PhpParser\Node\Scalar\String_($id));
        }
        $stmts = [
            new Stmt\Return_(new Expr\Array_($items, ['kind' => Expr\Array_::KIND_SHORT])),
        ];
        $printer = new PrettyPrinter\Standard(['shortArraySyntax' => true]);
        return "<?php\n\n"
            . "// Generated by php-js-transpile. Do not edit.\n"
            . "// Ahead-of-time compiled JavaScript (docs/aot-php.md). Each entry is a\n"
            . "// native function body for the id it is keyed by; register the array with\n"
            . "// BuiltinRegistry::registerHost() before running the matching bytecode.\n\n"
            . $printer->prettyPrint($stmts) . "\n";
    }
}
